package com.neatandclean;

public class Database {

    Integer [] photo = {

            R.drawable.bulky1,
            R.drawable.mixed1,
            R.drawable.glass1,
            R.drawable.metal1,
            R.drawable.paper1,
            R.drawable.bio1,
            R.drawable.bulky2,
            R.drawable.mixed2,
            R.drawable.glass2,
            R.drawable.metal2,
            R.drawable.paper2,
            R.drawable.bio2,
            R.drawable.bulky3,
            R.drawable.mixed3,
            R.drawable.glass3,
            R.drawable.metal3,
            R.drawable.paper3,
            R.drawable.bio3,
            R.drawable.bulky4,
            R.drawable.mixed4,
            R.drawable.glass4,
            R.drawable.metal4,
            R.drawable.paper4,
            R.drawable.bio4,
            R.drawable.bulky5,
            R.drawable.mixed5,
            R.drawable.glass5,
            R.drawable.metal5,
            R.drawable.paper5,
            R.drawable.bio5,
           /* R.drawable.bulky_5,
            R.drawable.mixed_5,
            R.drawable.glass_5,
            R.drawable.metalnplastic_5,
            R.drawable.paper_5,
            R.drawable.bio_5,
            R.drawable.bulky_6,
            R.drawable.mixed_6,
            R.drawable.glass_6,
            R.drawable.metalnplastic_6,
            R.drawable.paper_6,
            R.drawable.bio_6,

            */


    };

    String[] answers = {
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            /*"Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",
            "Bulky Waste",
            "Mixed Waste",
            "Glass",
            "Metal and Plastic",
            "Paper",
            "Bio",

            */
    };
}
